# PBS configuration
queue: expressbw
project: g40
walltime: 1:00:00
jobname: 1deg_jra55_iaf
ncpus: 252
mem: 500GB

runspersub: 1

shortpath: /short/v45

# Model configuration
name: common
model: access-om2
input: /short/public/access-om2/input_38570c62/common_1deg_jra55
submodels:
    - name: atmosphere
      model: yatm
      #exe: /short/public/access-om2/bin/yatm_1044c48e.exe
      exe: /short/public/access-om2/bin/yatm_e8ad3723.exe
      input: /short/public/access-om2/input_38570c62/yatm_1deg
      ncpus: 1

    - name: ocean
      model: mom
      exe: /short/public/access-om2/bin/fms_ACCESS-OM_afe80bfd.x
      input: /short/public/access-om2/input_38570c62/mom_1deg
      ncpus: 216

    - name: ice
      model: cice5
      exe: /short/public/access-om2/bin/cice_auscom_360x300_24p_076b14f2.exe
      input: /short/public/access-om2/input_38570c62/cice_1deg
      ncpus: 24

platform:
    nodesize: 28

# Misc
runlog: True
stacksize: unlimited
collate:
    enable: True
    walltime: 1:00:00
    queue: express
    ncpus: 2
    # flags: -n4 -z -m -r
    # mpi: true

mpirun: --mca orte_base_help_aggregate 0
qsub_flags: -W umask=027 -m a
# postscript: ls.sh
